Fix "gissues hasn't closes correctly" #66
Failed to find a suitable Github repository URL, sorry!

Error detected while processing function <SNR>16_showIssue:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 150, in showIssueBuffer
vim.error: Vim(python):Traceback (most recent call last):

E382: Cannot write, 'buftype' option is not set

This caused because after not found GH repo script doesn't stop.

Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>